### ISSUE TITLE
Suggestions for forms

### ISSUE THREAD

**Issue by laurpaik-zz** [newayliu1/Supermarket-Management-System#1]
Hi Wei,
Under `create` when I typed my price, I included a dollar sign and it defaulted to 0 when I created my eggs. Is there a way to have the `$` before the form field so that people know they don't have to type it? Also, when I typed `2.75` in that field, it rounded down to `2`, so it needs to be a `float`, not an `integer`.

In your date forms, if you change the type from `string` to `date`, you can get a calendar! then you don't have to worry about people putting it in ISO8601 format.

I'm still going through this! I'll keep filing issues if I think of ways to make it clearer!

**Comment by laurpaik-zz** [comment]
Maybe rename your Field 1, Field 2, and Field 3 and the last form (in `<h3>`) as 
```
"Search a product"
"Create a product" 
"Add product to inventory"
"Order Queue" 
```

or something?

**Comment by newayliu1** [comment]
Fixed, thank you Lauren.
